POST http://localhost:3000/reports
Content-Type: application/json

{
    "make": "Toyota",
    "model": "Corolla",
    "year": 1983,
    "mileage": 98770,
    "longitude": 0,
    "latitude": 0,
    "price": 4560000
}