### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "amani@gmail.com",
    "password": "jojojo"
}


### Find user by Id
GET http://localhost:3000/auth/1

### Find all users
GET http://localhost:3000/auth

### Find user by email address
GET http://localhost:3000/auth?email=amaneeei@gmail.com

### Delete user by id
DELETE http://localhost:3000/auth/2

### Update user
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
    "email": "amaniss777666s@gmail.com"
}

